package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Appuser generated by hbm2java
 */
public class Appuser  implements java.io.Serializable {


     private Long idUser;
     private String name;
     private String surname;
     private String username;
     private String password;
     private String phoneNum;
     private String email;
     private boolean isAdmin;
     private boolean isApproved;
     private Date lastLogin;
     private int warnings;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);
     private Set<Notification> notifications = new HashSet<Notification>(0);
     private Set<Review> reviews = new HashSet<Review>(0);

    public Appuser() {
    }
    
    public Appuser (String name, String surname, String username, String password, String phoneNum, String email) {
        this.name = name;
        this.surname = surname;
        this.username = username;
        this.password = password;
        this.phoneNum = phoneNum;
        this.email = email;
        //podrazumevane vrednosti
    }
	
    public Appuser(String name, String surname, String username, String password, String phoneNum, String email, boolean isAdmin, boolean isApproved, Date lastLogin, int warnings) {
        this.name = name;
        this.surname = surname;
        this.username = username;
        this.password = password;
        this.phoneNum = phoneNum;
        this.email = email;
        this.isAdmin = isAdmin;
        this.isApproved = isApproved;
        this.lastLogin = lastLogin;
        this.warnings = warnings;
    }
    
    public Appuser(String name, String surname, String username, String password, String phoneNum, String email, boolean isAdmin, boolean isApproved, Date lastLogin, int warnings, Set<Ticket> tickets, Set<Notification> notifications, Set<Review> reviews) {
       this.name = name;
       this.surname = surname;
       this.username = username;
       this.password = password;
       this.phoneNum = phoneNum;
       this.email = email;
       this.isAdmin = isAdmin;
       this.isApproved = isApproved;
       this.lastLogin = lastLogin;
       this.warnings = warnings;
       this.tickets = tickets;
       this.notifications = notifications;
       this.reviews = reviews;
    }
   
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public boolean isIsApproved() {
        return this.isApproved;
    }
    
    public void setIsApproved(boolean isApproved) {
        this.isApproved = isApproved;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public int getWarnings() {
        return this.warnings;
    }
    
    public void setWarnings(int warnings) {
        this.warnings = warnings;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }




}


