package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Long idFestival;
     private String name;
     private Date dateStart;
     private Date dateEnd;
     private String location;
     private String details;
     private int capacityPerDay;
     private int maxTicketsPerUser;
     private int packetPrice;
     private int dayPrice;
     private long views;
     private long ticketsBought;
     private String facebook;
     private String twitter;
     private String instagram;
     private String youtube;
     private boolean canceled;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Performance> performances = new HashSet<Performance>(0);
     private Set<Gallery> galleries = new HashSet<Gallery>(0);
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Festival() {
    }

	
    public Festival(String name, Date dateStart, Date dateEnd, String location, String details, int capacityPerDay, int maxTicketsPerUser, int packetPrice, int dayPrice, long views, long ticketsBought, boolean canceled) {
        this.name = name;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.location = location;
        this.details = details;
        this.capacityPerDay = capacityPerDay;
        this.maxTicketsPerUser = maxTicketsPerUser;
        this.packetPrice = packetPrice;
        this.dayPrice = dayPrice;
        this.views = views;
        this.ticketsBought = ticketsBought;
        this.canceled = canceled;
    }
    public Festival(String name, Date dateStart, Date dateEnd, String location, String details, int capacityPerDay, int maxTicketsPerUser, int packetPrice, int dayPrice, long views, long ticketsBought, String facebook, String twitter, String instagram, String youtube, boolean canceled, Set<Review> reviews, Set<Performance> performances, Set<Gallery> galleries, Set<Ticket> tickets) {
       this.name = name;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.location = location;
       this.details = details;
       this.capacityPerDay = capacityPerDay;
       this.maxTicketsPerUser = maxTicketsPerUser;
       this.packetPrice = packetPrice;
       this.dayPrice = dayPrice;
       this.views = views;
       this.ticketsBought = ticketsBought;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.youtube = youtube;
       this.canceled = canceled;
       this.reviews = reviews;
       this.performances = performances;
       this.galleries = galleries;
       this.tickets = tickets;
    }
   
    public Long getIdFestival() {
        return this.idFestival;
    }
    
    public void setIdFestival(Long idFestival) {
        this.idFestival = idFestival;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public int getCapacityPerDay() {
        return this.capacityPerDay;
    }
    
    public void setCapacityPerDay(int capacityPerDay) {
        this.capacityPerDay = capacityPerDay;
    }
    public int getMaxTicketsPerUser() {
        return this.maxTicketsPerUser;
    }
    
    public void setMaxTicketsPerUser(int maxTicketsPerUser) {
        this.maxTicketsPerUser = maxTicketsPerUser;
    }
    public int getPacketPrice() {
        return this.packetPrice;
    }
    
    public void setPacketPrice(int packetPrice) {
        this.packetPrice = packetPrice;
    }
    public int getDayPrice() {
        return this.dayPrice;
    }
    
    public void setDayPrice(int dayPrice) {
        this.dayPrice = dayPrice;
    }
    public long getViews() {
        return this.views;
    }
    
    public void setViews(long views) {
        this.views = views;
    }
    public long getTicketsBought() {
        return this.ticketsBought;
    }
    
    public void setTicketsBought(long ticketsBought) {
        this.ticketsBought = ticketsBought;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }
    public boolean isCanceled() {
        return this.canceled;
    }
    
    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Performance> getPerformances() {
        return this.performances;
    }
    
    public void setPerformances(Set<Performance> performances) {
        this.performances = performances;
    }
    public Set<Gallery> getGalleries() {
        return this.galleries;
    }
    
    public void setGalleries(Set<Gallery> galleries) {
        this.galleries = galleries;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


