package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1



/**
 * Gallery generated by hbm2java
 */
public class Gallery  implements java.io.Serializable {


     private Long idItem;
     private Festival festival;
     private String path;
     private int type;
     private boolean isApproved;

    public Gallery() {
    }

    public Gallery(Festival festival, String path, int type, boolean isApproved) {
       this.festival = festival;
       this.path = path;
       this.type = type;
       this.isApproved = isApproved;
    }
   
    public Long getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Long idItem) {
        this.idItem = idItem;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public boolean isIsApproved() {
        return this.isApproved;
    }
    
    public void setIsApproved(boolean isApproved) {
        this.isApproved = isApproved;
    }




}


