package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Performance generated by hbm2java
 */
public class Performance  implements java.io.Serializable {


     private Long idPerformance;
     private Festival festival;
     private String artist;
     private Date dateStart;
     private Date dateEnd;
     private Date timeStart;
     private Date timeEnd;
     private boolean canceled;

    public Performance() {
    }

    public Performance(Festival festival, String artist, Date dateStart, Date dateEnd, Date timeStart, Date timeEnd, boolean canceled) {
       this.festival = festival;
       this.artist = artist;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.timeStart = timeStart;
       this.timeEnd = timeEnd;
       this.canceled = canceled;
    }
   
    public Long getIdPerformance() {
        return this.idPerformance;
    }
    
    public void setIdPerformance(Long idPerformance) {
        this.idPerformance = idPerformance;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
    public Date getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }
    public Date getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }
    public boolean isCanceled() {
        return this.canceled;
    }
    
    public void setCanceled(boolean canceled) {
        this.canceled = canceled;
    }




}


