package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1



/**
 * Review generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private Long idReview;
     private Appuser appuser;
     private Festival festival;
     private String nameFestival;
     private String comment;
     private int rating;

    public Review() {
    }

    public Review(Appuser appuser, Festival festival, String nameFestival, String comment, int rating) {
       this.appuser = appuser;
       this.festival = festival;
       this.nameFestival = nameFestival;
       this.comment = comment;
       this.rating = rating;
    }
   
    public Long getIdReview() {
        return this.idReview;
    }
    
    public void setIdReview(Long idReview) {
        this.idReview = idReview;
    }
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public String getNameFestival() {
        return this.nameFestival;
    }
    
    public void setNameFestival(String nameFestival) {
        this.nameFestival = nameFestival;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


