package db;
// Generated Feb 10, 2017 10:08:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Long idTicket;
     private Appuser appuser;
     private Festival festival;
     private Date dateFor;
     private int amount;
     private Date reservedAt;
     private boolean bought;
     private boolean expired;

    public Ticket() {
    }

    public Ticket(Appuser appuser, Festival festival, int amount) {
        this.appuser = appuser;
        this.festival = festival;
        this.amount = amount;
    }
    
    public Ticket(Appuser appuser, Festival festival, int amount, boolean bought) {
         this.appuser = appuser;
         this.festival = festival;
         this.amount = amount;
         this.bought = bought;
        
    }
	
    public Ticket(Appuser appuser, Festival festival, int amount, Date reservedAt, boolean bought, boolean expired) {
        this.appuser = appuser;
        this.festival = festival;
        this.amount = amount;
        this.reservedAt = reservedAt;
        this.bought = bought;
        this.expired = expired;
    }
    public Ticket(Appuser appuser, Festival festival, Date dateFor, int amount, Date reservedAt, boolean bought, boolean expired) {
       this.appuser = appuser;
       this.festival = festival;
       this.dateFor = dateFor;
       this.amount = amount;
       this.reservedAt = reservedAt;
       this.bought = bought;
       this.expired = expired;
    }
   
    public Long getIdTicket() {
        return this.idTicket;
    }
    
    public void setIdTicket(Long idTicket) {
        this.idTicket = idTicket;
    }
    public Appuser getAppuser() {
        return this.appuser;
    }
    
    public void setAppuser(Appuser appuser) {
        this.appuser = appuser;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Date getDateFor() {
        return this.dateFor;
    }
    
    public void setDateFor(Date dateFor) {
        this.dateFor = dateFor;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getReservedAt() {
        return this.reservedAt;
    }
    
    public void setReservedAt(Date reservedAt) {
        this.reservedAt = reservedAt;
    }
    public boolean isBought() {
        return this.bought;
    }
    
    public void setBought(boolean bought) {
        this.bought = bought;
    }
    public boolean isExpired() {
        return this.expired;
    }
    
    public void setExpired(boolean expired) {
        this.expired = expired;
    }




}


